import { mapSources } from './map-sources';
import type { SourceReview } from '../src/domain/model';
export const istatSource:SourceReview={
 id:'istat-situas',name:'Anagrafica dei comuni · SITUAS',publisher:'Istat',
 url:'https://www.istat.it/classificazione/codici-dei-comuni-delle-province-e-delle-regioni/',status:'approved',
 license:{name:'CC BY 4.0',url:'https://creativecommons.org/licenses/by/4.0/',commercialUse:'allowed',attribution:'Fonte: Istat, SITUAS. Normalizzazione e ricerca: Che luogo è?'},
 reviewedAt:'2026-10-04',coverage:'Tutti i comuni vigenti restituiti da SITUAS alla data richiesta',granularity:'Comune amministrativo',
 limitations:['Snapshot: non è una connessione in tempo reale a ogni ricerca.','Non contiene coordinate, confini o indicatori.','Fusioni e ricodifiche richiedono una nuova importazione.','Data di ultimo aggiornamento del singolo record non fornita.','Nessun SLA o limite numerico di chiamata verificato: importazione unica, nessuna chiamata upstream per ricerca.'],
};
const candidates:[string,string,string,string,string,string,string][]=[
 ['maptiler','Cartografia e rilievo 3D','MapTiler','https://www.maptiler.com/terms/cloud/','Nazionale, dettaglio variabile','Tessere vettoriali e DEM','Chiave e piano da configurare. Free limitato a uso non commerciale e ricerca/sviluppo. Attribuzioni obbligatorie; nessuna estrazione dei dati dalle tessere.'],
 ['istat-demografia','Popolazione ed età','Istat','https://www.istat.it/classificazioni-e-strumenti/web-services-sdmx/','Da verificare per dataset e anno','Comune, secondo dataset','Licenza generale CC BY 4.0; selezione dataflow, periodi e corrispondenza codici ancora da verificare.'],
 ['open-meteo-climate','Clima e serie storiche','Open-Meteo','https://open-meteo.com/en/pricing','Nazionale su griglia','Griglia del modello','Piano e condizioni commerciali da selezionare. Separare rianalisi, misure e proiezioni; non sono osservazioni puntuali del comune.'],
 ['ispra','Frane e alluvioni','ISPRA · IdroGEO','https://idrogeo.isprambiente.it/api/','Italia, secondo dataset','Poligono e aggregato comunale','Verificare licenza della versione, scenario e aggiornamento. Pericolosità ed esposizione non equivalgono al rischio individuale.'],
 ['cams','Qualità dell’aria','CAMS / Open-Meteo','https://open-meteo.com/en/docs/air-quality-api','Europa, secondo modello','Griglia','Stime modellistiche: distinguere da centraline. Licenze CAMS e accesso API da verificare insieme.'],
 ['geoapify','Servizi e geocodifica','Geoapify','https://www.geoapify.com/places-api/','Italia, copertura variabile','Punto di interesse / indirizzo','Chiave, quote, attribuzione e conservazione da verificare. Dati OSM non garantiscono censimento completo.'],
 ['scuole','Scuole','Ministero dell’Istruzione','https://dati.istruzione.it/opendata/opendata/sparql/endpoint/','Italia, secondo dataset','Istituto / plesso','Verificare dataset, licenza, anno scolastico e disponibilità endpoint SPARQL.'],
 ['salute','Farmacie e strutture sanitarie','Ministero della Salute','https://www.dati.salute.gov.it/','Italia, secondo dataset','Struttura','Verificare licenza IODL 2.0 per dataset, aggiornamento e formato. Eventuali download saranno esposti dalla nostra API.'],
 ['case','Quotazioni immobiliari','OpenAPI / dati OMI','https://console.openapi.com/it/apis/realestate/documentation','Italia, secondo prodotto','Zona OMI e tipologia immobiliare','Servizio commerciale: contratto, redistribuzione, cache e costi da verificare. Intervalli di quotazione, non prezzo certo di un immobile.'],
 ['sicurezza','Denunce e criminalità','Istat / Ministero dell’Interno','https://www.istat.it/statistiche-per-temi/giustizia-e-sicurezza/','Da verificare','Spesso provincia, non comune','Nessuna API nazionale comunale approvata. Non attribuire valori provinciali al singolo comune o quartiere.'],
 ['redditi','Redditi dichiarati','MEF','https://www1.finanze.gov.it/finanze/analisi_stat/public/index.php?opendata=yes','Comuni, secondo anno fiscale','Comune','Download ufficiali da verificare; API di consultazione nativa non verificata. Redditi dichiarati diversi da patrimonio e reddito di tutti i residenti.'],
 ['copernicus','Copertura del suolo e alberi','Copernicus','https://documentation.dataspace.copernicus.eu/APIs.html','Italia, secondo prodotto','Raster','Selezionare prodotto, risoluzione, periodo, licenza e quote. Aggregazione comunale solo con confini compatibili.'],
 ['natura2000','Aree protette','EEA','https://bio.discomap.eea.europa.eu/arcgis/rest/services/ProtectedSites/Natura2000Sites/MapServer','Rete Natura 2000','Poligoni','Verificare versione e condizioni. Natura 2000 non coincide con tutte le aree protette italiane.'],
 ['gbif','Osservazioni di biodiversità','GBIF','https://www.gbif.org/terms','Copertura disomogenea','Occorrenza georeferenziata','Licenza per dataset: escludere CC BY-NC per uso commerciale. Presenza di segnalazioni non misura ricchezza biologica completa.'],
 ['agcom','Connettività','AGCOM','https://www.agcom.it/mappatura-delle-reti-di-accesso-ad-internet','Italia, secondo strato','Indirizzo / area di copertura','Verificare licenza e riuso API; copertura dichiarata non equivale alla velocità misurata.'],
];
export const sourceRegistry:SourceReview[]=[istatSource,...mapSources,...candidates.map(([id,name,publisher,url,coverage,granularity,limit])=>({id,name,publisher,url,coverage,granularity,status:'pending' as const,license:{name:null,url:null,commercialUse:'unverified' as const,attribution:null},reviewedAt:null,limitations:[limit,'Fonte candidata: dossier di integrazione ancora da completare. Nessun dato caricato.']}))];
