import {Link} from 'react-router-dom';
import {ArrowUpRight,ChartNoAxesCombined,Database} from 'lucide-react';
import {categories,indicators} from '../data/catalog';
import type {ClimateResponse,IndicatorGroup,Observation} from '../domain/model';
import {type GroupState,groups,groupLabels,downloadJson} from '../domain/presentation';
import {displayValue,periodLabel} from '../domain/comparison';
import {IndicatorCard} from './IndicatorCard';
import {CategoryIcon} from './Icons';
import {ValueVisual,AgcomCredit} from './DataVisual';
const captions:Record<string,string>={clima:'Il contesto climatico del 2025, da rianalisi. Non descrive il microclima di una strada.',rischi:'Scenari di pericolosità. Le superfici degli scenari possono sovrapporsi e non vanno sommate.',demografia:'Composizione della popolazione nel censimento 2021. Una fotografia storica, non una stima di oggi.',economia:'Redditi fiscali e attività economiche hanno basi e anni diversi. Non sono reddito netto disponibile o opportunità di lavoro.',natura:'Suolo artificiale e segnalazioni naturalistiche descrivono aspetti diversi: non un unico indice di natura.',connettivita:'Copertura FTTH stimata da AGCOM. Non garantisce velocità o attivazione al singolo civico.',scuole:'Unità anagrafiche scolastiche. I conteggi non misurano qualità, capienza o numero di edifici.',servizi:'Strutture registrate nel comune. Il numero non misura distanza, orari o accessibilità.',aria:'Previsioni orarie e medie annuali restano separate. Una griglia non è una centralina.',territorio:'Identità amministrativa e patrimonio registrato, con le epoche delle rispettive fonti.',case:'Quotazioni per zona e tipologia: dati ancora da collegare.',sicurezza:'Le statistiche provinciali non possono essere attribuite al singolo comune.'};
export function MunicipalityDashboard({name,slug,code,observations,extra,climate,climateState,climateError,retry,selected,onSelect}:{name:string;slug:string;code:string;observations:Observation[];extra:Record<IndicatorGroup,GroupState>;climate:ClimateResponse|null;climateState:string;climateError:string;retry:()=>void;selected:string;onSelect:(id:string)=>void}){
 const find=(id:string)=>observations.find(o=>o.indicatorId===id);
 const available=observations.filter(o=>o.value!==null).length;
 const pending=climateState==='loading'||groups.some(g=>extra[g].loading);
 const insight=(category:string)=>{
  const n=(id:string)=>find(id)?.value;
  if(category==='economia'&&n('income-recipients')!=null&&n('taxpayers')!=null)return `La media del reddito complessivo usa ${displayValue(n('income-recipients')!,'contribuenti')} dichiarazioni con reddito significativo, su ${displayValue(n('taxpayers')!,'contribuenti')} contribuenti. Questo spiega perché non è una media su tutti i residenti.`;
  if(category==='demografia'&&n('young')!=null&&n('elderly')!=null)return `Nel censimento 2021, ${displayValue(n('young')!,'%')} residenti su 100 hanno meno di 15 anni e ${displayValue(n('elderly')!,'%')} su 100 ne hanno almeno 65. Sono quote della popolazione, non previsioni del suo futuro.`;
  if(category==='natura'&&n('soil-change')!=null)return n('soil-change')!>0?`Tra il 2023 e il 2024 il consumo di suolo è aumentato di ${displayValue(n('soil-change')!,'ha')} ettari netti, già al netto del ripristino rilevato dalla fonte.`:n('soil-change')!<0?`Tra il 2023 e il 2024 il ripristino ha superato il nuovo consumo di ${displayValue(-n('soil-change')!,'ha')} ettari. Non è una misura degli alberi recuperati.`:'La fonte riporta una variazione netta nulla del consumo di suolo nel 2023–2024. Non significa assenza di trasformazioni.';
  return null;
 };
 const card=(id:string)=>{const d=indicators.find(i=>i.id===id)!;const state=d.providerGroup?extra[d.providerGroup]:null;return <IndicatorCard key={id} definition={d} observation={find(id)} sourceName={state?.data?.sourceName} loading={d.category==='clima'?climateState==='loading':state?.loading} error={d.category==='clima'?climateError:state?.error||(state?.data?.status==='configuration-required'?state.data.message:undefined)}/>;};
 return <section className="dashboard" aria-labelledby="dashboard-title"><div className="dashboard-heading"><div><span className="eyebrow">IL LUOGO, ATTRAVERSO I DATI</span><h2 id="dashboard-title">Dentro {name}</h2><p>Persone, ambiente e vita quotidiana. Ogni prospettiva ha la sua fonte.</p></div><Link className="primary compare-link" to={`/confronta?a=${encodeURIComponent(slug)}`}><ChartNoAxesCombined size={19}/> Confronta un altro comune</Link></div>
 <div className="dashboard-meta" role="status"><span>{available} indicatori con dato{pending?' · caricamento in corso':''}</span><span>Epoche diverse, indicate in ogni scheda</span><span>Nessun voto complessivo</span></div>
 {selected==='tutte'&&<div className="headline-grid">{['population','income-mean','soil-percent','ftth'].map(id=>{const d=indicators.find(i=>i.id===id)!,o=find(id);return <button key={id} className={`headline-stat ${d.category}`} onClick={()=>onSelect(d.category)}><span>{d.name}</span><strong>{o?.value!=null?displayValue(o.value,o.unit):'—'} <small>{o?.value!=null?o.unit:''}</small></strong><span>{o?.value!=null?`${periodLabel(o)} · ${o.sourceId}`:'Dato non disponibile'} <ArrowUpRight size={14}/></span></button>;})}</div>}
 <nav className="category-filters dashboard-filters" aria-label="Sezioni della dashboard"><button aria-pressed={selected==='tutte'} onClick={()=>onSelect('tutte')}>Panoramica</button>{categories.map(c=><button key={c.id} aria-pressed={selected===c.id} onClick={()=>onSelect(c.id)}><CategoryIcon id={c.id} size={17}/>{c.short}</button>)}</nav>
 <div className="dashboard-panels">{categories.filter(c=>selected==='tutte'||selected===c.id).map(c=>{
 const defs=indicators.filter(i=>i.category===c.id),present=defs.filter(d=>find(d.id)?.value!=null),missing=defs.filter(d=>!present.includes(d));
 const ages=['young','adults','elderly'].map(find);const ageComplete=ages.every(o=>o?.value!=null&&o.value>=0&&o.value<=100)&&Math.abs(ages.reduce((s,o)=>s+(o?.value??0),0)-100)<.05;
 return <article className={`dashboard-panel ${c.color} ${selected!=='tutte'?'panel-expanded':''}`} key={c.id} id={`section-${c.id}`}><header><span className={`category-icon ${c.color}`}><CategoryIcon id={c.id}/></span><div><h3>{c.name}</h3><span className="panel-count">{present.length?`${present.length} dati consultabili`:'Dati da completare'}</span></div></header><p className="panel-caption">{captions[c.id]}</p>{insight(c.id)&&<p className="panel-insight">{insight(c.id)}</p>}
 {c.id==='demografia'&&ageComplete&&<div className="age-composition"><div className="age-track" aria-hidden="true">{ages.map((o,i)=><span key={o!.id} className={`age-${i}`} style={{width:`${o!.value}%`}}/>)}</div><div className="age-legend">{ages.map((o,i)=><span key={o!.id}><i className={`age-${i}`}/>{['Meno di 15','15–64','65 e oltre'][i]}: <b>{displayValue(o!.value!,'%')}%</b></span>)}</div><small>Quote originali · censimento 2021 · arrotondamenti della fonte</small></div>}
 <div className="panel-values">{present.map(d=><ValueVisual key={d.id} definition={d} observation={find(d.id)!}/>)}</div>
 {!present.length&&<div className="panel-empty">{(c.id==='clima'&&climateState==='loading')||pending&&defs.some(d=>d.providerGroup&&extra[d.providerGroup].loading)?'Caricamento della fonte…':(c.id==='clima'||defs.some(d=>d.providerGroup))?'Nessun valore utilizzabile al momento. Apri lo stato delle fonti per conoscere il motivo.':'Fonte da integrare. Non vengono mostrati valori dimostrativi.'}</div>}
 {c.id==='connettivita'&&<AgcomCredit/>}
 {c.id==='scuole'&&!!extra.schools.data?.entries?.length&&<details className="school-directory"><summary>Esplora nomi e indirizzi delle scuole</summary><ul>{extra.schools.data.entries.map(e=><li key={e.id}><strong>{e.title}</strong><p>{e.description}</p></li>)}</ul></details>}
 <details className="panel-details"><summary><Database size={16}/> Dati originali, metodo e fonti ({defs.length})</summary><div className="indicator-grid">{present.map(d=>card(d.id))}{missing.map(d=>card(d.id))}</div></details>
 {!!missing.length&&<p className="panel-foot">{missing.length} indicatori senza valore consultabile. Motivi e metodo nelle schede.</p>}
 </article>;})}</div>
 <details className="dashboard-sources"><summary>Stato delle fonti, download e richieste non riuscite</summary><div className="climate-notice"><strong>NASA POWER · clima 2025</strong><p>{climateError||'Rianalisi su cella di 0,5° × 0,625°, non media sul territorio comunale.'}</p>{climate&&<button className="text-button" onClick={()=>downloadJson(climate.original.text,`NASA-${code}.json`)}>Scarica risposta originale</button>}</div><div className="source-loads">{groups.map(g=><div className="source-load" key={g}><strong>{groupLabels[g]} · {extra[g].loading?'Caricamento':extra[g].error?'Errore':extra[g].data?.status==='configuration-required'?'Configurazione richiesta':'Risposta caricata'}</strong><p>{extra[g].error||extra[g].data?.message}</p>{extra[g].data?.original&&<button className="text-button" onClick={()=>downloadJson(extra[g].data!.original!.text,`${g}-${code}.json`)}>Scarica record originali</button>}</div>)}</div><button className="secondary" onClick={retry}>Riprova il caricamento delle fonti</button></details>
 </section>;
}
