import {ComparePage} from './components/ComparePage';
import {MunicipalityDashboard} from './components/MunicipalityDashboard';
import {groups,freshGroups} from './domain/presentation';
import { useEffect,useRef,useState } from 'react';
import { Link,NavLink,Route,Routes,useLocation,useParams,useSearchParams } from 'react-router-dom';
import { MapPin,Compass,BookOpen,Check,Info,Menu,X,Database,ShieldCheck,ArrowUpRight } from 'lucide-react';
import { categories } from './data/catalog';
import { httpProvider } from './providers/http';
import type { DataProvider,MunicipalityReport,RegistryStatus,SourceReview,ClimateResponse } from './domain/model';
import { Search } from './components/Search';
import { TerritoryMap } from './components/TerritoryMap';
import { CategoryIcon } from './components/Icons';
import { formatDate,formatNumber } from './domain/format';
function Header(){const [menu,setMenu]=useState(false);const location=useLocation();useEffect(()=>setMenu(false),[location.pathname]);return <header className="site-header"><div className="header-inner"><Link to="/" className="brand" aria-label="Che luogo è? — Home"><span className="brand-symbol"><MapPin size={24}/></span><span>che luogo è<span className="brand-question">?</span></span></Link><button className="mobile-menu icon-button" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-controls="main-navigation" aria-label={menu?'Chiudi menu':'Apri menu'}>{menu?<X/>:<Menu/>}</button><nav id="main-navigation" aria-label="Navigazione principale" className={menu?'nav-open':''}><NavLink to="/" end>Esplora</NavLink><NavLink to="/confronta">Confronta</NavLink><NavLink to="/fonti-e-metodologia">Fonti e metodo</NavLink><span className="version-label">IN COSTRUZIONE</span></nav></div></header>;}
function Footer(){return <footer className="site-footer"><Link to="/" className="footer-brand">che luogo è?</Link><p>Un luogo non si riassume in un voto.</p><Link to="/fonti-e-metodologia">Come leggiamo i dati <BookOpen size={15}/></Link></footer>;}
function useStatus(provider:DataProvider){const [status,setStatus]=useState<RegistryStatus|null>(null);useEffect(()=>{const c=new AbortController();provider.getStatus(c.signal).then(setStatus).catch(()=>{});return ()=>c.abort();},[provider]);return status;}
function Home({provider}:{provider:DataProvider}){const status=useStatus(provider);return <>
 <section className="home-hero"><div className="hero-content"><span className="eyebrow"><span className="eyebrow-line"/> OGNI LUOGO HA QUALCOSA DA RACCONTARE</span><h1>Che luogo è<span>?</span></h1><p className="hero-description">Tutto quello che dovresti sapere su un luogo,<br className="desktop-break"/> prima di viverci.</p><Search provider={provider}/><div className="quick-places"><span>Esplora</span><Link to="/comuni/carimate"><MapPin size={15}/> Carimate</Link><Link to="/comuni/roma">Roma</Link><Link to="/confronta">Confronta due comuni →</Link></div></div>
 <div className="hero-aside"><div className="national-card"><span className="eyebrow">PARTIAMO DA CIÒ CHE SAPPIAMO</span><div className="national-title"><span>Ogni comune.<br/>La sua storia.</span><MapPin size={48}/></div><div className="national-count"><strong>{status?formatNumber(status.count):'Italia'}</strong><span>{status?'comuni nell’anagrafica ufficiale':'Anagrafica nazionale ISTAT'}</span></div><p>Nomi, codici e appartenenza amministrativa da ISTAT. Clima, rischi naturali, demografia storica, redditi, scuole, farmacie, consumo di suolo e segnalazioni naturalistiche, con fonti e limiti dichiarati.</p><div className="national-foot"><span>{status?`Riferimento: ${formatDate(status.referenceDate)}`:'Caricamento della copertura…'}</span><Link to="/fonti-e-metodologia">Verifica le fonti <ArrowUpRight size={16}/></Link></div></div></div></section>
 <section className="category-section" aria-labelledby="category-heading"><div className="section-heading"><div><span className="eyebrow">GUARDA PIÙ DA VICINO</span><h2 id="category-heading">Un luogo, più prospettive.</h2></div><p>Ogni categoria racconta una parte della storia.</p></div><div className="category-grid">{categories.map(c=><Link className={`category-card ${c.color}`} key={c.id} to={`/comuni/carimate?categoria=${c.id}`}><div className="category-card-top"><span className={`category-icon ${c.color}`}><CategoryIcon id={c.id}/></span></div><h3>{c.short}</h3><p>{c.description}</p><span className="category-link">{c.id==='aria'?'Previsioni · chiave da configurare':['case','sicurezza'].includes(c.id)?'Fonte da collegare':'Esplora i dati →'}</span></Link>)}</div><p className="roadmap-copy">Il catalogo comprende anche case, sicurezza e connettività: la fibra FTTH è collegata ad AGCOM e le integrazioni incomplete sono indicate in ogni sezione. <Link to="/fonti-e-metodologia">Vedi le fonti candidate →</Link></p></section>
 <section className="principles" aria-label="I principi del progetto"><div className="principle-intro"><ShieldCheck size={25}/><h2>Capire, prima<br/>di giudicare.</h2></div><div><Check size={18}/><h3>Solo dati verificabili</h3><p>Fonte, periodo e limiti accanto a ogni informazione.</p></div><div><Check size={18}/><h3>Nessuna classifica assoluta</h3><p>Ogni categoria si legge separatamente.</p></div><Link to="/fonti-e-metodologia">Leggi il metodo <BookOpen size={17}/></Link></section>
 <div className="project-note"><Info size={17}/><p>Progetto in costruzione. Nessun valore simulato. Dove non abbiamo un dato, lo diciamo.</p></div>
 </>;}
function MunicipalityPage({provider}:{provider:DataProvider}){
 const {slug}=useParams();const [params,setParams]=useSearchParams();const selected=categories.some(c=>c.id===params.get('categoria'))?params.get('categoria')!:'tutte';
 const [climate,setClimate]=useState<ClimateResponse|null>(null),[climateState,setClimateState]=useState<'loading'|'ready'|'error'>('loading'),[climateError,setClimateError]=useState(''),[retry,setRetry]=useState(0);
 const [extra,setExtra]=useState(freshGroups);const [mapOpen,setMapOpen]=useState(false);
 const [report,setReport]=useState<MunicipalityReport|null>(null);const [status,setStatus]=useState<'loading'|'ready'|'error'>('loading');
 useEffect(()=>{const c=new AbortController();setReport(null);setStatus('loading');provider.getMunicipality(slug??'',c.signal).then(r=>{if(!c.signal.aborted){setReport(r);setStatus('ready');if(r)document.title=`${r.municipality.name} | Che luogo è?`;}}).catch(()=>{if(!c.signal.aborted)setStatus('error');});return ()=>c.abort();},[provider,slug]);
 useEffect(()=>{const c=new AbortController();setClimate(null);setClimateState('loading');setClimateError('');
  if(!provider.getClimate){setClimateState('error');setClimateError('Provider climatico non configurato.');return;}
  provider.getClimate(slug??'',c.signal).then(data=>{if(!c.signal.aborted){setClimate(data);setClimateState('ready');}}).catch(error=>{if(!c.signal.aborted){setClimateState('error');setClimateError(error.message);}});return ()=>c.abort();
 },[provider,slug,retry]);
 useEffect(()=>{
  const c=new AbortController();setExtra(freshGroups());
  for(const group of groups){
   const request=provider.getIndicators?.(slug??'',group,c.signal)??Promise.reject(new Error('Provider non configurato'));
   request.then(data=>{if(!c.signal.aborted)setExtra(state=>({...state,[group]:{data,loading:false,error:''}}));}).catch(error=>{if(!c.signal.aborted)setExtra(state=>({...state,[group]:{data:null,loading:false,error:error.message}}));});
  }
  return ()=>c.abort();
 },[provider,slug,retry]);
 if(status==='loading')return <div className="empty-page" role="status">Caricamento della scheda…</div>;
 if(status==='error')return <div className="empty-page"><h1>Scheda non disponibile</h1><p>Non siamo riusciti a caricare i dati. Riprova tra poco.</p><Link to="/">Torna alla ricerca</Link></div>;
 if(!report)return <div className="empty-page"><h1>Comune non trovato</h1><p>Cerca un nome o un codice ISTAT nell’anagrafica nazionale.</p><Link to="/">Torna alla ricerca</Link></div>;
 const observations=[...(climate?.observations??[]),...groups.flatMap(g=>extra[g].data?.observations??[])];
 const {municipality:m,provenance:p}=report;
 return <div className="page-container"><div className="breadcrumb"><Link to="/">Esplora</Link><span>/</span><span>{m.name}</span></div><div className="municipality-heading"><div><span className="eyebrow">{m.region} · {m.province}</span><h1>{m.name}</h1><p>Il territorio, una prospettiva alla volta.</p></div><Link className="secondary" to="/"><Compass size={18}/> Cambia comune</Link></div>
 <details className="map-disclosure" onToggle={e=>setMapOpen(e.currentTarget.open)}><summary><MapPin size={18}/> Esplora la mappa 3D e l’identità del comune</summary>{mapOpen&&<div className="place-intro"><div className="place-map"><TerritoryMap report={report} provider={provider}/></div><aside className="reading-guide"><span className="eyebrow">ANAGRAFICA UFFICIALE</span><h2>Questo luogo<br/>ha un’identità.</h2><dl className="identity"><dt>Codice ISTAT</dt><dd>{m.istatCode}</dd><dt>Regione</dt><dd>{m.region}</dd><dt>Unità territoriale sovracomunale</dt><dd>{m.province}</dd><dt>Data di riferimento</dt><dd>{formatDate(p.referenceDate)}</dd></dl><Link to="/fonti-e-metodologia">Fonte: ISTAT · CC BY 4.0</Link></aside></div>}</details>
 <details className="record-provenance"><summary><Database size={17}/> Provenienza e record originale ISTAT</summary><div><p>{p.attribution}</p><dl className="identity"><dt>Natura del dato</dt><dd>Anagrafica ufficiale censita</dd><dt>Acquisizione</dt><dd>{formatDate(p.retrievedAt)}</dd><dt>Aggiornamento del singolo record</dt><dd>Non fornito dalla fonte</dd><dt>Risoluzione</dt><dd>{p.spatialResolution}</dd><dt>Affidabilità</dt><dd>Alta per l’anagrafica · {p.reliability.reason}</dd><dt>Metodo</dt><dd>{p.methodVersion} · nomi invariati, slug di navigazione derivati</dd></dl><a href={p.sourceUrl} target="_blank" rel="noreferrer">Apri l’API originale ISTAT ↗</a><p className="checksum">SHA-256 del download: {p.sha256}</p><pre>{JSON.stringify(report.original,null,2)}</pre></div></details>
 <MunicipalityDashboard name={m.name} slug={m.slug} code={m.id} observations={observations} extra={extra} climate={climate} climateState={climateState} climateError={climateError} retry={()=>setRetry(n=>n+1)} selected={selected} onSelect={id=>setParams(id==='tutte'?{}:{categoria:id})}/></div>;

}
function Methodology({provider}:{provider:DataProvider}){
 const [sources,setSources]=useState<SourceReview[]>([]);const [error,setError]=useState(false);const status=useStatus(provider);
 useEffect(()=>{const c=new AbortController();provider.getSources(c.signal).then(setSources).catch(()=>{if(!c.signal.aborted)setError(true);});return ()=>c.abort();},[provider]);
 return <div className="page-container method-page"><div className="breadcrumb"><Link to="/">Esplora</Link><span>/</span><span>Fonti e metodologia</span></div><span className="eyebrow">LA TRASPARENZA, PRIMA DI TUTTO</span><h1>Dietro ogni dato,<br/>una fonte. E dei limiti.</h1><p className="method-lead">Separiamo ciò che osserviamo da ciò che calcoliamo. Rendiamo visibile ciò che ancora non sappiamo. Nessun dato inventato, nessun voto complessivo del luogo.</p>
 <div className="method-layout"><aside className="method-nav"><a href="#stato">Stato attuale</a><a href="#tipi">Come leggere i dati</a><a href="#fonti">Registro delle fonti</a><a href="#passi">Prossimi passi</a></aside><div className="method-content">
 <section id="stato"><h2>La base è reale. Il resto è in costruzione.</h2><p>È attiva l’anagrafica nazionale dei comuni ISTAT, acquisita tramite API e servita dalla nostra API di ricerca. Conserviamo il download originale e la sua impronta SHA-256. Non interroghiamo ISTAT a ogni ricerca.</p>{status&&<p>{formatNumber(status.count)} comuni · riferimento {formatDate(status.referenceDate)} · acquisizione {formatDate(status.retrievedAt)}. I dati sono una fotografia a questa data, non un flusso aggiornato in tempo reale.</p>}<p>Sono collegati tre indicatori climatici del 2025: temperatura media, giorni con Tmax &gt; 30 °C e precipitazioni. La fonte NASA POWER/MERRA-2 è una rianalisi su griglia, non una misura comunale. Sono collegate le API ISPRA IdroGEO per frane (2024), alluvioni (2020) e demografia ISTAT del censimento 2021, e GBIF per le segnalazioni CC0 nel riquadro geografico del comune. Le farmacie provengono dal download JSON ministeriale del 5 ottobre 2026, importato ed esposto dalla nostra API: non è un collegamento ministeriale in tempo reale. Le previsioni orarie dell’aria CAMS/Open-Meteo richiedono una chiave commerciale; le medie annue restano da integrare. Sono inoltre collegati i redditi MEF dell’anno d’imposta 2024, le anagrafi MIM 2026/27 (escluse le autonomie di Aosta, Trento e Bolzano) e il consumo di suolo ISPRA/SNPA fino al 2024: download ufficiali importati ed esposti dalla nostra API, aggiornati solo con una nuova importazione. È collegata anche la reportistica AGCOM sulla fibra FTTH al 30 giugno 2026, come stima di copertura e non velocità reale. Restano incompleti trasporti, copertura arborea, aree protette, prezzi delle case e sicurezza. La mappa usa confini statistici ISTAT al 1 gennaio 2026. Il globo e lo sfondo stradale sono navigabili. Il satellite Esri richiede la configurazione della chiave del sito. Cartografia e rilievo 3D dipendono dalla disponibilità dei servizi cartografici e dal supporto grafico del browser. Se non sono caricabili, resta il confine reale in vista statica. Cinque comuni non hanno una geometria validata disponibile. La ricerca per indirizzo non è attiva. Il confronto tra due comuni è disponibile, con controllo di compatibilità per indicatore e senza classifica complessiva.</p><div className="callout"><Info size={21}/><p><strong>“Non disponibile” non significa zero.</strong> Non permette di dedurre sicurezza, qualità o assenza di criticità.</p></div></section>
 <section id="tipi"><h2>Valori originali e interpretazioni separate.</h2><div className="data-types"><div><span className="type-tag">Osservato / censito</span><p>Misure o registri pubblicati dalla fonte, con periodo, risoluzione e copertura.</p></div><div><span className="type-tag">Elaborato</span><p>Calcolo riproducibile: input originali, formula e versione del metodo conservati.</p></div><div><span className="type-tag">Previsione</span><p>Stima futura, con modello, scenario, orizzonte e incertezza documentati.</p></div><div><span className="type-tag">Non disponibile</span><p>Nessuna sostituzione con dati simulati, stime arbitrarie o zeri.</p></div></div><p>I punteggi non sono attivi. Eventuali valutazioni avranno una metodologia specifica e resteranno separate dal dato: non saranno presentate come verità scientifiche né aggregate in un voto del comune.</p><p>Un dato provinciale non diventa comunale. Una griglia non diventa una centralina. Un valore medio non descrive ogni strada o immobile.</p></section>
 <section id="fonti"><h2>Il registro delle fonti</h2><p>Le fonti indicate come attive alimentano le schede o la cartografia. Le altre sono candidate: prima dell’integrazione completeremo il dossier su licenza, API, copertura, granularità, limiti e affidabilità.</p>{error?<p role="alert">Registro non disponibile. Riprova più tardi.</p>:!sources.length?<p role="status">Caricamento delle fonti…</p>:sources.map(source=><article className="source-box" key={source.id}><span className="badge">{source.status==='approved'?'Attiva · verificata':source.status==='configuration-required'?'Richiede configurazione del sito':'Candidata · da verificare'}</span><h3>{source.name}</h3><p>{source.publisher}</p><dl><dt>Copertura</dt><dd>{source.coverage}</dd><dt>Granularità</dt><dd>{source.granularity}</dd><dt>Licenza</dt><dd>{source.license.name??'Da verificare sul dataset e sul piano scelto'}</dd><dt>Revisione completa</dt><dd>{source.reviewedAt?formatDate(source.reviewedAt):'Non completata'}</dd></dl><ul>{source.limitations.map(limit=><li key={limit}>{limit}</li>)}</ul>{source.url&&<a href={source.url} target="_blank" rel="noreferrer">Documentazione della fonte ↗</a>}{source.license.url&&<p><a href={source.license.url}>Licenza e attribuzione</a> · {source.license.attribution}</p>}</article>)}</section>
 <section id="passi"><h2>Una fonte alla volta.</h2><ol className="source-checks"><li><strong>Territorio e mappa 3D</strong><p>Confini storici e punti di centraggio derivati integrati. Da verificare i servizi cartografici in un ambiente con supporto 3D, completare le geometrie mancanti e seguire le variazioni territoriali successive.</p></li><li><strong>Demografia</strong><p>Popolazione, struttura per età e variazione: stesso anno e codici compatibili.</p></li><li><strong>Clima, aria e rischi naturali</strong><p>Distinguere stazioni, modelli e scenari. Conservare dati originali e trasformazioni.</p></li><li><strong>Servizi, natura e contesto economico</strong><p>Scuole, salute, trasporti, aree protette, case, redditi, sicurezza e connettività secondo disponibilità effettiva.</p></li><li><strong>Confronto e pubblicazione</strong><p>Confronti soltanto su indicatori compatibili. Verifica finale dell’esperienza, accessibilità e indicizzazione prima del deploy.</p></li></ol></section>
 </div></div></div>;
}
function NotFound(){return <div className="empty-page"><Compass size={44}/><h1>Qui non c’è ancora un luogo.</h1><p>La pagina che cerchi non esiste.</p><Link className="primary" to="/">Torna alla ricerca</Link></div>;}
export function App({provider=httpProvider}:{provider?:DataProvider}){
 const location=useLocation();const main=useRef<HTMLElement>(null);const previous=useRef(location.pathname);
 useEffect(()=>{document.title=location.pathname==='/confronta'?'Confronta comuni | Che luogo è?':location.pathname==='/fonti-e-metodologia'?'Fonti e metodologia | Che luogo è?':'Che luogo è? — Conosci il tuo prossimo luogo';if(previous.current!==location.pathname){window.scrollTo(0,0);main.current?.focus({preventScroll:true});previous.current=location.pathname;}},[location.pathname]);
 return <><a className="skip-link" href="#contenuto">Salta al contenuto</a><Header/><main id="contenuto" ref={main} tabIndex={-1}><Routes><Route path="/" element={<Home provider={provider}/>}/><Route path="/confronta" element={<ComparePage provider={provider}/>}/><Route path="/comuni/:slug" element={<MunicipalityPage provider={provider}/>}/><Route path="/fonti-e-metodologia" element={<Methodology provider={provider}/>}/><Route path="*" element={<NotFound/>}/></Routes></main><Footer/></>;
}
